info:
  title: Airtable
  version: "1.0.4"
openapi: 3.0.0
paths:
  /{baseId}/{table}:
    parameters:
      - $ref: "#/components/parameters/baseId"
      - $ref: "#/components/parameters/table"
    get:
      operationId: get_records
      parameters:
        in: query
        name: sort
        required: false
        schema:
          type: array
          items:
            type:
              object
        style: deepObject
      - in: query
        name: maxRecords
        schema:
          format: int32
          type: integer
      - in: query
        name: filterByFormula
        schema:
          type: string
      - description: The offset parameter, if available
        in: query
        name: offset
        required: false
        schema:
          type: string
      - description: The page size
        in: query
        name: pageSize
        required: false
        schema:
          type: integer
      responses:
        200:
          description: ""
    post:
      operationId: create_record
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: New record to add
        required: true
      responses:
        200:
          description: ""
  /{baseId}/{table}/{recordId}:
    parameters:
      - $ref: "#/components/parameters/baseId"
      - $ref: "#/components/parameters/table"
      - $ref: "#/components/parameters/recordId"
    get:
      operationId: get_record
      responses:
        200:
          description: ""
    delete:
      operationId: delete_record
      responses:
        200:
          description: ""
    patch:
      operationId: update_record
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: Record to update
        required: true
      responses:
        200:
          description: ""
components:
  parameters:
    baseId:
      description: "The Airtable base ID. This can be found as part of the API documentation URL. Go to https://airtable.com/api and select the base you're interested in, then find the base ID in the resulting URL: https://airtable.com/<baseId>/api/docs."
      in: path
      name: baseId
      required: true
      schema:
        type: string
    table:
      description: The table being referenced within the base. This table must already exist.
      in: path
      name: table
      required: true
      schema:
        type: string
    recordId:
      description: The record being referenced.
      in: path
      name: recordId
      required: true
      schema:
        type: string

servers:
- url: https://api.airtable.com/v0