info:
  title: Airtable
  version: 1.0.0
openapi: 3.0.0
paths:
  /{baseId}/{table}:
    get:
      operationId: get_records
      parameters:
      - description: The airtable base id
        in: path
        name: baseId
        required: true
        schema:
          type: string
      - description: The table you are querying within the base
        in: path
        name: table
        required: true
        schema:
          type: string
      - explode: true
        in: query
        name: sort
        required: false
        schema:
          type: array
          items:
            type:
              object
        style: deepObject
      - in: query
        name: maxRecords
        schema:
          format: int32
          type: integer
      - in: query
        name: filterByFormula
        schema:
          type: string
      - description: The offset parameter, if available
        in: query
        name: offset
        required: false
        schema:
          type: string
      - description: The page size
        in: query
        name: pageSize
        required: false
        schema:
          type: integer
      responses:
        200:
          description: ""
    post:
      operationId: create_record
      parameters:
      - description: The airtable base id
        in: path
        name: baseId
        required: true
        schema:
          type: string
      - description: The table you are querying within the base
        in: path
        name: table
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: New record to add
        required: true
      responses:
        200:
          description: ""
  /{baseId}/{table}/{recordId}:
    get:
      operationId: get_record
      parameters:
      - description: The airtable base id
        in: path
        name: baseId
        required: true
        schema:
          type: string
      - description: The table you are querying within the base
        in: path
        name: table
        required: true
        schema:
          type: string
      - description: The record you want to fetch
        in: path
        name: recordId
        required: true
        schema:
          type: string
      responses:
        200:
          description: ""
    delete:
      operationId: delete_record
      parameters:
      - description: The airtable base id
        in: path
        name: baseId
        required: true
        schema:
          type: string
      - description: The table you are querying within the base
        in: path
        name: table
        required: true
        schema:
          type: string
      - description: The record you want to delete
        in: path
        name: recordId
        required: true
        schema:
          type: string
      responses:
        200:
          description: ""
    patch:
      operationId: update_record
      parameters:
      - description: The airtable base id
        in: path
        name: baseId
        required: true
        schema:
          type: string
      - description: The table you are querying within the base
        in: path
        name: table
        required: true
        schema:
          type: string
      - description: The record you want to update
        in: path
        name: recordId
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: Record to update
        required: true
      responses:
        200:
          description: ""
servers:
- url: https://api.airtable.com/v0
