info:
  title: Airtable
  version: 1.0.0
openapi: 3.0.0
paths:
  /{baseId}/{table}:
    parameters:
      - $ref: "#/components/parameters/baseId"
      - $ref: "#/components/parameters/table"
    get:
      operationId: get_records
      parameters:
      - name: maxRecords
        in: query
        description: The maximum total number of records that will be returned in your requests. If this value is larger than pageSize (which is 100 by default), you may have to load multiple pages to reach this total. 
        schema:
          format: int32
          type: integer
      - name: filterByFormula
        in: query
        schema:
          type: string
      - description: The offset parameter, if available
        in: query
        name: offset
        required: false
        schema:
          type: string
      - name: sort
        explode: true
        in: query
        required: false
        schema:
          type: array
          items:
            type:
              object
        style: deepObject
      - name: pageSize
        in: query
        description: The number of records returned in each request. Must be less than or equal to 100. Default is 100.
        required: false
        schema:
          type: integer
      responses:
        200:
          description: ""
    post:
      operationId: create_record
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: New record to add
        required: true
      responses:
        200:
          description: ""
  /{baseId}/{table}/{recordId}:
    parameters:
      - $ref: "#/components/parameters/baseId"
      - $ref: "#/components/parameters/table"
      - $ref: "#/components/parameters/recordId"
    get:
      operationId: get_record
      responses:
        200:
          description: ""
    delete:
      operationId: delete_record
      responses:
        200:
          description: ""
    patch:
      operationId: update_record
      requestBody:
        content:
          application/json:
            schema:
              type: string
        description: Record to update
        required: true
      responses:
        200:
          description: ""
components:
  parameters:
    baseId:
      description: "The Airtable base ID. This can be found as part of the API documentation URL. Go to https://airtable.com/api and select the base you're interested in, then find the base ID in the resulting URL: https://airtable.com/<baseId>/api/docs."
      in: path
      name: baseId
      required: true
      schema:
        type: string
    table:
      description: The table being referenced within the base. This table must already exist.
      in: path
      name: table
      required: true
      schema:
        type: string
    recordId:
      description: The record being referenced.
      in: path
      name: recordId
      required: true
      schema:
        type: string

servers:
- url: https://api.airtable.com/v0
